[build]
  # This will be run the site build
  command = "CI=false yarn build"
  # This is the directory is publishing to netlify's CDN
  publish = "build"
  # functions build directory
  functions = "functions-build"